---
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-bucket-{{ uuidv4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.crossplane.infrastructure | quote }}
spec:
  forProvider:
    region: us-east-2
  providerConfigRef:
    name: default
