name: Setup Helm
description: This action sets up Docker, kubectl, and Helm in the GitHub Actions environment.
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4
    
    - name: Set up Helm
      uses: azure/setup-helm@v4^
    
    # configure kubeseal
    - name: Install Kubeseal
      shell: bash
      run: |
        set -eu
        curl -sL https://github.com/bitnami-labs/sealed-secrets/releases/download/v${{ inputs.version }}/kubeseal-${{ inputs.version }}-linux-amd64.tar.gz \
          -o $GITHUB_WORKSPACE/kubeseal-${{ inputs.version }}-linux-amd64.tar.gz
        tar xzvf $GITHUB_WORKSPACE/kubeseal-${{ inputs.version }}-linux-amd64.tar.gz
        mkdir -p $GITHUB_WORKSPACE/bin
        mv $GITHUB_WORKSPACE/{,bin/}kubeseal
        chmod +x $GITHUB_WORKSPACE/bin/kubeseal
        echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH
    
    # configure aws credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
