name: Setup Helm
run-name: Setting up Helm
on: [push]
jobs:
  SpinUpCluster:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
      
      - name: Set up Helm
        uses: azure/setup-helm@v4
