apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-eu1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/diegopso/crossplane-example.git
    path: aws-eu1/apps
    targetRevision: cluster-creation
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
