apiVersion: v1
kind: Secret
metadata:
  name: sealed-secrets-initial-key
  annotations:
    argocd.argoproj.io/hook: PreSync
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "tls.pem" | b64enc }}