apiVersion: v1
kind: Secret
metadata:
  name: sealed-secrets-initial-key
  annotations:
    helm.sh/hook: pre-install # for install when only Helm is present
    argocd.argoproj.io/hook: PreSync # for later syncs when ArgoCD is in controll
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "tls.pem" | b64enc }}