name: Setup Kind
description: This action sets up Kind and a Kind cluster in the GitHub Actions environment.
runs:
  using: "composite"
  steps:
    - name: Install kind
      shell: bash
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Create kind cluster
      shell: bash
      run: |
        kind create cluster --wait 60s
    
    - name: Get Cluster status
      shell: bash
      run: |
        kubectl wait --for=condition=ready pods --namespace=kube-system -l k8s-app=kube-dns
        kubectl get nodes -o wide
        kubectl get pods -A
