apiVersion: v2
name: base-cluster-application
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "0.1.0"
icon: https://docs.crossplane.io/favicon-32x32.png

# dependencies:
#   - name: crossplane
#     version: "1.20.0"
#     repository: https://charts.crossplane.io/stable