apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/diegopso/crossplane-example.git
    targetRevision: cluster-creation
    path: aws-eu1/crossplane
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
