name: Setup SOPS
description: This action sets up Docker, kubectl, and Helm in the GitHub Actions environment.

inputs:
  resource:
    required: true
    description: "Resource to wait for"
  max_attempts:
    required: false
    default: "10"
    description: "Resource to wait for"

runs:
  using: "composite"
  steps:
    - name: Wait for ${{ inputs.resource }} to be ready
      shell: bash
      run: |
        retry=1

        while [[ $retry -le $max_retries ]]; do
          if kubectl wait ${{ inputs.resource }} --for=condition=Ready --all --timeout 1s; then
            echo "Succeeded."
            break
          else
            echo "Attempt $retry/$max_retries failed. Retrying in 6 seconds..."
            sleep 6
            ((retry++))
          fi
        done

        if [[ $retry -gt $max_retries ]]; then
          echo "Wait failed after $max_retries attempts."
          exit 1
        fi
